version: '3.4'

services:
  app:
    image: jlesage/firefox:v1.12.0
    deploy:
      labels:
        app.version: "v77.0.1"
      mode: replicated
      replicas: 1
    environment:
      DISPLAY_WIDTH: 1920
      DISPLAY_HEIGHT: 900
      USER_ID: 1002
      GROUP_ID: 1002
      UMASK: 022
      TZ: Europe/Amsterdam
      ENABLE_CJK_FONT: 1
    networks:
      - default_net
    ports:
      - target: 5800
        published: 5801
        protocol: tcp
        mode: host
    volumes:
      - type: volume
        source: config
        target: /config
      - type: bind
        source: /share/Data
        target: /storage
      # increase container shared memory size with bind mapping with host
      - type: bind
        source: /dev/shm
        target: /dev/shm


networks:
  default_net:
    external: true

volumes:
  config:
