version: '3.8'

services:
  app:
    image: jlesage/handbrake:v1.23.2
    cap_add:
      - SYS_NICE
    environment:
      DISPLAY_WIDTH: 1920
      DISPLAY_HEIGHT: 1080
      USER_ID: 0
      GROUP_ID: 0
      UMASK: 022
      TZ: Europe/Amsterdam
      ENABLE_CJK_FONT: 1
      APP_NICENESS: 0
    networks:
      - portainerce_net
    ports:
      - target: 5800
        published: 5800
    volumes:
      - config:/config:rw
      - storage:/storage:rw
      - watch:/watch:rw
      - type: bind
        source: /share/Data
        target: /storage/data
        read_only: true
      - type: bind
        source: /share/Downloads
        target: /storage/downloads
        read_only: true
      - type: bind
        source: /share/Data
        target: /output
    deploy:
      mode: replicated
      replicas: 1

networks:
  portainerce_net:
    external: true

volumes:
  config:
  storage:
  watch:
