version: '3.8'

services:
  app:
    image: jlesage/mkvtoolnix:v1.51.1
    environment:
      DISPLAY_WIDTH: 1920
      DISPLAY_HEIGHT: 1080
      USER_ID: 0
      GROUP_ID: 0
      UMASK: 022
      TZ: Europe/Amsterdam
      ENABLE_CJK_FONT: 1
    ports:
      - target: 5800
        published: 5803
    volumes:
      - config:/config:rw
      - storage:/storage:rw
      - type: bind
        source: /share/Data
        target: /storage/data
      - type: bind
        source: /share/Downloads
        target: /storage/downloads
    deploy:
      mode: replicated
      replicas: 1

networks:

volumes:
  config:
  storage:
