version: '3.4'

services:
  app:
    image: jlesage/mkvtoolnix:v1.44.0
    deploy:
      labels:
        app.version: "v50.0.0"
      mode: replicated
      replicas: 1
    environment:
      DISPLAY_WIDTH: 1920
      DISPLAY_HEIGHT: 900
      USER_ID: 1005
      GROUP_ID: 1006
      SUP_GROUP_IDS: 1005
      UMASK: 022
      TZ: Europe/Amsterdam
      ENABLE_CJK_FONT: 1
    ports:
      - target: 5800
        published: 5803
        protocol: tcp
        mode: host
    volumes:
      - config:/config
      - storage:/storage:rw
      - /share/Data:/storage/data:rw
      - /share/Downloads:/storage/downloads:rw

volumes:
  config:
  storage:
