version: '3.4'

services:
  app:
    image: mikenye/picard:2.4.2
    deploy:
      labels:
        app.version: "v2.4.2"
      mode: replicated
      replicas: 1
    environment:
      DISPLAY_WIDTH: 1920
      DISPLAY_HEIGHT: 900
      USER_ID: 1005
      GROUP_ID: 1006
      SUP_GROUP_IDS: 1005
      UMASK: 022
      TZ: Europe/Amsterdam
      ENABLE_CJK_FONT: 1
    dns:
      - 1.1.1.1
      - 1.0.0.1
    networks:
      - default_net
    ports:
      - target: 5800
        published: 5802
        protocol: tcp
        mode: host
    volumes:
      - config:/config
      - storage:/storage:rw
      - /share/Data:/storage/data:rw
      - /share/Attic:/storage/attic:rw
      - /share/Music:/storage/music:rw

networks:
  default_net:
    external: true

volumes:
  config:
  storage:
