# Use 'docker stack' to deploy, does not work with docker-compose
version: '3.4'

services:
  agent:
    image: portainer/agent:2.1.0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - agentnet
    deploy:
      mode: global
      placement:
        constraints: [node.platform.os == linux]

  ui:
    depends_on:
      - agent
    image: portainer/portainer-ce:2.1.1
    command: -H tcp://tasks.agent:9001 --tlsskipverify
    ports:
      - target: 9000
        published: 9000
        protocol: tcp
        mode: host
    networks:
      - agentnet
      - net
    volumes:
      - data:/data
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]

networks:
  agentnet:
    driver: overlay
    attachable: true
  net:
    driver: overlay
    attachable: true

volumes:
  data:
