version: '3.4'

services:
  agent:
    image: portainer/agent:2.0.0
    networks:
      - net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    deploy:
      mode: global
      placement:
        constraints: [node.platform.os == linux]

networks:
  net:
    driver: overlay
    attachable: false
