version: '3.4'

services:
  ui:
    image: portainer/portainer:1.24.1
    environment:
      TZ: Europe/Stockholm
    command: -H unix:///var/run/docker.sock
    networks:
      - net
    ports:
      - target: 9000
        published: 9000
        protocol: tcp
        mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - data:/data
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]

networks:
  net:
    driver: overlay
    attachable: true

volumes:
  data:
