version: '3.8'

services:
  ui:
    image: ghcr.io/linuxserver/qbittorrent:version-14.3.4.99202104180633-7350-2c8f322afubuntu20.04.1
    deploy:
      mode: replicated
      replicas: 1
    environment:
      PUID: 0
      PGID: 0
      UMASK_SET: 022
      TZ: Europe/Amsterdam
      WEBUI_PORT: 8080
    networks:
      - qbt-net
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
        mode: host
    volumes:
      - type: volume
        source: config
        target: /config
      - type: bind
        source: /share/Data
        target: /downloads

networks:
  qbt-net:
    external: true

volumes:
  config:
